project:
  type: website
  output-dir: docs

website:
  title: "Lewis A. Jones"
  site-url: https://www.lewisajones.com
  description: "Personal website"
  image: "gallery/Arolla.jpg"
  favicon: "icons/coral.png"
  search: false
  open-graph: 
    image: "gallery/Arolla.jpg"
    image-width: 500
    image-height: 500
    locale: en-GB
  twitter-card: 
    title: Lewis A. Jones
    description: The personal website of Lewis A. Jones
    image: "gallery/Arolla.jpg"
    image-width: 500
    image-height: 500
    card-style: summary
    creator: "@LewisAlanJones"
    site: "@LewisAlanJones"
  navbar:
    pinned: true
    title: "Lewis A. Jones"
    logo-alt: "Dr Lewis A. Jones"
    background: transparent
    right:    
      - text: "About"
        href: index.qmd
      - text: "Research"
        href: research/index.qmd
      - text: "Projects"
        menu:
          - text: "EDiTH (UKRI185)"
            icon: "graph-up"
            href: projects/edith/index.qmd
      - text: "CV"
        href: experience/index.qmd
      - text: "Publications"
        href: publications/index.qmd
      - text: "Software"
        menu:
          - text: "palaeoverse"
            icon: "gear-fill"
            href: software/index.qmd#palaeoverse
          - text: "rphylopic"
            icon: "bug-fill"
            href: software/index.qmd#rphylopic
          - text: "rmacrostrat"
            icon: "hammer"
            href: software/index.qmd#rmacrostrat
          - text: "sepkoski"
            icon: "graph-up"
            href: software/index.qmd#sepkoski
      - text: "Gallery"
        file: gallery/index.qmd
      - text: "{{< iconify fa6-brands:bluesky >}}"
        href: "https://bsky.app/profile/lewisajones.bsky.social"
      - icon: github
        href: "https://github.com/LewisAJones"
      - icon: envelope-fill
        href: "mailto:Lewis.Jones@ucl.ac.uk"
      - icon: mortarboard-fill
        href: "https://scholar.google.com/citations?user=X0AvsOkAAAAJ&hl"
  page-footer: 
    background: "#1A213A"
    left: |
      © Copyright 2025 Lewis A. Jones
    center: |
      [![](/images/palaeoverse.png){fig-alt="Palaeoverse" height=25px}](https://palaeoverse.org)
    right: 
      - text: "{{< iconify fa6-brands:bluesky >}}"
        href: "https://bsky.app/profile/lewisajones.bsky.social"
      - icon: github
        href: "https://github.com/LewisAJones"
      - icon: envelope-fill
        href: "mailto:Lewis.Jones@ucl.ac.uk"
      - icon: mortarboard-fill
        href: "https://scholar.google.com/citations?user=X0AvsOkAAAAJ&hl"
format:
  html:
    page-layout: full
    theme:
      - theme.scss
      - brand
    css: styles.css
    toc: true
    smooth-scroll: true
    link-external-newwindow: true

editor: source

