---
editor: source
toc: false
---

# Experience

## Research summary

Palaeobiologist examining the macroecological and macroevolutionary history of reef-building organisms by integrating interdisciplinary tools and sources of information, such as ecological modelling, Earth system modelling, and fossil occurrence datasets. An additional significant theme of research has been evaluating the influence of data incompleteness on perceptions of the geological past. Currently investigating the drivers of marine biodiversity hotspots throughout the Cenozoic and reconstructing their evolutionary history.

**Macroecology and biodiversity** | **Fossil record bias** | **Corals and reef ecosystems** | **Palaeoclimate** | **R programming**

## Education

**PhD in Palaeobiology** (2016&ndash;2020)  
Imperial College London, London, UK  
Research advisors: Prof. Philip D. Mannion & Prof. Peter A. Allison  
Thesis title: On the detectability of latitudinal biodiversity gradients in deep time

**MPhysGeog in Physical Geography** (2011&ndash;2015)  
University of Hull, Hull, UK  
Research advisor: Prof. David P.G. Bond  
Thesis title: The End-Triassic mass extinction. An investigation of the British Geological Record: testing for the role of volcanism and ocean anoxia

**Chartered Management Institute (Level 5) in Management and Leadership** (2012&ndash;2015)  
Leeds University Officer Training Corps, Leeds, UK

## Employment

**NERC Independent Research Fellow** (2024&ndash;current)  
Department of Earth Sciences, University College London, London, UK

**Juan de la Cierva Postdoctoral Research Fellow** (2023&ndash;2024)  
Mapas Lab, Centro de Investigación Mariña, Universidade de Vigo, Vigo, Spain

**European Research Council Postdoctoral Research Assistant** (2021&ndash;2022)  
Mapas Lab, Centro de Investigación Mariña, Universidade de Vigo, Vigo, Spain

**Graduate Teaching Assistant** (2016&ndash;2021)  
Department of Earth Science and Engineering, Imperial College London, London, UK

**Student Hall's Warden** (2016&ndash;2021)  
Woodward Buildings, Imperial College London, London, UK

**British Army Officer Cadet** (2012&ndash;2015)  
Leeds University Officer Training Corps, Leeds, UK

**Sales Assistant** (2010&ndash;2012)  
Republic Ltd, Grimsby and Hull, UK

**Baker** (2008&ndash;2010)  
Muffin Break, Grimsby, UK

## Research visits

**University of Vienna, Vienna, Austria** (April&ndash;June, 2023)  
Visiting researcher in the Conservation Palaeobiology and Historical Ecology Lab (PI: Prof. Martin Zuschin)

## Publications

### **Peer-reviewed publications**

1. **Lewis A. Jones** and Mathew Domeier (2024). A Phanerozoic gridded dataset for palaeogeographic reconstructions. *Scientific Data* 11 (710), 1&ndash;7. DOI: [10.1038/s41597-024-03468-w](https://doi.org/10.1038/s41597-024-03468-w).

2.	Alfio A. Chiarenza, Juan L. Cantalapiedra, **Lewis A. Jones**, Sara Gamboa, Sofía Galván, Alexander Farnsworth, Paul J. Valdes, Graciela Sotelo, and Sara Varela (2024). Early Jurassic origin of avian endothermy and thermophysiological diversity in dinosaurs. *Current Biology* 34, 1&ndash;11. DOI: [10.1016/j.cub.2024.04.051](https://doi.org/10.1016/j.cub.2024.04.051).

3.	Kilian Eichenseer and **Lewis A. Jones** (2024). Bayesian multi-proxy reconstruction of early Eocene latitudinal temperature gradients. *Climate of the Past* 20, 349&ndash;362. DOI: [10.5194/cp-20-349-2024](https://doi.org/10.5194/cp-20-349-2024).

4.  Lucas Buffan, **Lewis A. Jones**, Mathew Domeier, Christopher R. Scotese, Sabin Zahirovic and Sara Varela (2023). Mind the Uncertainty: Global Plate Model choice impacts deep-time palaeobiological studies. *Methods in Ecology and Evolution* 14 (12), 3007&ndash;3019. DOI:[10.1111/2041-210X.14204](https://doi.org/10.1111/2041-210X.14204).

5.  William Gearty and **Lewis A. Jones** (2023). rphylopic: An R package for fetching, transforming, and visualising PhyloPic silhouettes. *Methods in Ecology and Evolution* 14 (11), 2700&ndash;2708. DOI:[10.1111/2041-210X.14221](https://doi.org/10.1111/2041-210X.14221).

6.  **Lewis A. Jones**, William Gearty, Bethany J. Allen, Kilian Eichenseer, Christopher D. Dean, Sofía Galván, Miranta Kouvari, Pedro L. Godoy, Cecily Nicholl, Lucas Buffan, Erin M. Dillon, Joseph T. Flannery-Sutherland and A. Alessandro Chiarenza (2023). palaeoverse: A community-driven R package to support palaeobiological analysis. *Methods in Ecology and Evolution* 14 (9), 2205&ndash;2215. DOI:[10.1111/2041-210X.14099](https://doi.org/10.1111/2041-210X.14099).

7.  **Lewis A. Jones**, Philip D. Mannion, Alexander Farnsworth, Fran Bragg, Daniel J. Lunt (2022). Climatic and tectonic drivers shaped the tropical distribution of coral reefs. *Nature Communications* 13 (3120), 1&ndash;10. DOI:[10.1038/s41467-022-30793-8](https://doi.org/10.1038/s41467-022-30793-8).

8.  **Lewis A. Jones** and Kilian Eichenseer (2022). Uneven spatial sampling distorts reconstructions of Phanerozoic seawater temperature. *Geology* 50 (2), 238&ndash;242. DOI:[10.1130/G49132.1](https://doi.org/10.1130/G49132.1).

9.  **Lewis A. Jones**, Christopher D. Dean, Philip D. Mannion, Alexander Farnsworth, Peter A. Allison (2021). Spatial sampling heterogeneity limits the detectability of deep time latitudinal biodiversity gradients. *Proceedings of the Royal Society B* 288 (1945), 20202762. DOI:[10.1098/rspb.2020.2762](https://doi.org/10.1098/rspb.2020.2762).

10.  **Lewis A. Jones**, Philip D. Mannion, Alexander Farnsworth, Paul Valdes, Sarah-Jane Kelland, and Peter A. Allison (2019). Coupling of palaeontological and neontological reef coral data improves forecasts of biodiversity responses under global climatic change. *Royal Society Open Science* 6 (4), 182111. DOI:[10.1098/rsos.182111](https://doi.org/10.1098/rsos.182111).

11.  Alfio Alessandro Chiarenza, Philip D. Mannion, Daniel Lunt, Alexander Farnsworth, **Lewis A. Jones**, Sarah-Jane Kelland, and Peter A. Allison (2019). Ecological niche modelling does not support climatically-driven dinosaur diversity decline before the Cretaceous/Paleogene mass extinction. *Nature Communications* 10 (1091), 1&ndash;14. DOI:[10.1038/s41467-019-08997-2](https://doi.org/10.1038/s41467-019-08997-2).

### **Theses**

1.  **Lewis A. Jones** (2020). On the detectability of latitudinal biodiversity gradients in deep time. PhD Thesis. Imperial College London. Supervisors: Prof. Philip D. Mannion and Prof. Peter A. Allison. DOI:[10.25560/100239](https://spiral.imperial.ac.uk/handle/10044/1/100239).

2.  **Lewis A. Jones** (2015). The end-Triassic mass extinction. An investigation of the British geological record: testing for the role of volcanism and ocean anoxia. Master Thesis. Supervisor: Prof. David Bond.

### **Other works**

1.  **Lewis A. Jones** (2023). [Palaeontology’s greatest ever graphs: The absence of evidence: spatial sampling bias in the fossil record](https://www.palass.org/publications/newsletter/archive/114/newsletter-no-114). *The Palaeontological Association Newsletter* 114.

2.  **Lewis A. Jones** (2022). [Book review: Timefulness: How thinking like a geologist can help save the world](https://www.palass.org/publications/newsletter/archive/110/newsletter-no-110). *The Palaeontological Association Newsletter* 110.

3.  Michael Stevens, Yiqiao Chen, Alex Stringer, Caitlin Clemmow, and **Lewis A. Jones** (2020). [Key factors driving obesity in the UK](https://drive.google.com/file/d/1MHWMo_bC1pw-hVEddibDvxsinlOK0Tjh/view). *GISRUK* 2020.

4.  **Lewis A. Jones** (2020). [Meeting report: 13th International Symposium of Fossil Cnidaria and Porifera](https://www.palass.org/sites/default/files/media/publications/newsletters/number_102/number_102.pdf). *The Palaeontological Association Newsletter* 102.

## Published software

1. **palaeoverse**: A community-driven R package to support data preparation and exploration for palaeobiological analyses.  
CRAN: [https://cran.r-project.org/web/packages/palaeoverse/](https://cran.r-project.org/web/packages/palaeoverse/)  
GitHub: [https://github.com/palaeoverse/palaeoverse](https://github.com/palaeoverse/palaeoverse)  

2. **rphylopic**: An R package for fetching, transforming, and visualising PhyloPic silhouettes.  
CRAN: [https://cran.r-project.org/web/packages/rphylopic/](https://cran.r-project.org/web/packages/rphylopic/)  
GitHub: [https://github.com/palaeoverse/rphylopic](https://github.com/palaeoverse/rphylopic)

3. **sepkoski**: A data R package of Sepkoski's Fossil Marine Animal Genera Compendium (Sepkoski, 2002). 
CRAN: [https://cran.r-project.org/web/packages/sepkoski/](https://cran.r-project.org/web/packages/sepkoski/)  
GitHub: [https://github.com/lewisajones/sepkoski](https://github.com/lewisajones/sepkoski)

4. **rmacrostrat**: An R package to fetch geologic data from the Macrostrat database.  
CRAN: [https://cran.r-project.org/web/packages/rmacrostrat/](https://cran.r-project.org/web//packages/rmacrostrat/)  
GitHub: [https://github.com/palaeoverse/rmacrostrat](https://github.com/palaeoverse/rmacrostrat/)  

## Academic awards and grants

**Addressing the origins of marine invertebrate diversity in computer simulations (INDICiOS)** (2024)  
Proyectos de Generación de Conocimiento (Knowledge Generation Projects), Spain  
Role: co-applicant, value: 345,000 EUR

**Elucidating diversity dynamics in marine tropical hotspots** (2024)  
Natural Environment Research Council Independent Research Fellowship, UK  
Role: applicant, value: 874,978 GBP

**Reconstructing the diversity dynamics and drivers of Cenozoic marine biodiversity hotspots** (2024)  
Norman Newell grant from the Paleontological Society, USA  
Role: applicant, value: 5000 USD

**rmacrostrat R package development workshop** (2024)  
Scientific Exchange grant from the Swiss National Science Fund, Switzerland  
Role: co-applicant, value: 5800 CHF

**MURKY: Mesophotic and turbid reefs as key ecosystems for the future?** (2023)  
Research workshop grant from the Paleosynthesis project, Friedrich-Alexander-Universität, Germany  
Role: co-applicant, value: 10,000 EUR

**R for Palaeobiologists: Workshop and Hackathon** (2023)  
Meeting support grant from The Paleontological Society, USA  
Role: co-applicant, value: 1000 USD

**R for Palaeobiologists: Workshop and Hackathon** (2022)  
Grant-in-Aid from The Palaeontological Association, UK  
Role: applicant, value: 2000 GBP

**Juan de la Cierva Fellowship** (2022)  
Agencia Estatal de Investigación, Spain  
Role: applicant, value: 64,800 EUR

**Doctoral Summer School for Advanced Spatial Modelling - Hackathon award** (2019)  
Awarded for best hackathon project, Centre for Advanced Spatial Analysis, University College London, London  
Value: 250 GBP

**13<sup>th</sup> International Symposium on Fossil Cnidaria and Porifera - Travel grant** (2019)  
Travel grant from The Palaeontological Association, UK  
Role: applicant, value: 220 EUR

**President's PhD Scholarship** (2016)  
Imperial College London, London, UK  
Role: applicant, value: 70,000 GBP

**Roger Ward thesis award** (2015)  
Awarded for best Master's thesis, University of Hull, Hull, UK  
Value: 50 GBP

## Invited presentations

**Computational Palaeobiology Mini-Symposium** (2024)  
Department of Biosystems Science and Engineering, ETH Zürich, Basel, Switzerland  
Oral: Mind the uncertainty: Global Plate Model choice impacts deep-time palaeobiological studies

**Methods in Ecology and Evolution: Live!** (2023)  
British Ecological Society, Online workshop  
Oral: Introduction to rphylopic: An R package for fetching, transforming, and visualising PhyloPic silhouettes

**Department of Palaeontology, University of Vienna, Austria** (2023)  
Oral: Into the palaeoverse: a community-driven R package

**PalaeoSIG (British Ecological Society): Masterclass in R** (2022)  
Oral: Into the palaeoverse: a community-driven R package

**Getech PLC** (2018)  
Oral: Ecological modelling in Geosciences

## Selected conference presentations

**12<sup>th</sup> North American Paleontological Convention** (Ann Arbor, Michigan, USA, 2024)  
Oral: Mind the uncertainty: Global Plate Model choice impacts deep-time palaeobiological studies  
Poster: palaeoverse: A community-driven R package to support palaeobiological analyses  
Poster: rmacrostrat: An R package for retrieving data from the Macrostrat geological database

**14<sup>th</sup> International Fossil Coral and Reef Society symposium** (Chęciny, Poland, 2023)  
Oral: Inverse latitudinal diversity gradients in Last Interglacial coral reef communities

**The Palaeontological Association: Annual Meeting** (Cork, Ireland, 2022)  
Poster: Niche characterisation is biased by limited and heterogeneous spatial sampling

**Simposio de Paleontologia del noroeste peninsular** (A Coruña, Spain, 2022)  
Poster: palaeoverse: a community-driven R package

**The Palaeontological Association: Annual Meeting** (Valencia, Spain, 2019)  
Oral: Poor spatial sampling coverage obscures our understanding of the latitudinal biodiversity gradient in deep time  
Poster: Uneven spatial sampling in Phanerozoic palaeoclimate curves

**13<sup>th</sup> International Symposium on Fossil Cnidaria and Porifera** (Modena, Italy, 2019)  
Oral: The evolution of the latitudinal biodiversity gradient in zooxanthellate corals

**The past is a foreign country: how much can the fossil record actually inform conservation?** (London, UK, 2019)  
Poster: Looking through the palaeontological window: reducing geographical and environmental bias in forecasting biodiversity responses

**Crossing the Palaeontological&ndash;Ecological Gap** (Leeds, UK, 2018)  
Oral: Absence of evidence is not evidence of absence: quantifying reef coral range shifts under global climatic change

**British Ecological Society - Macroecology** (St. Andrews, UK, 2018)  
Oral: Anthropogenic climate change and transitional distribution ranges of reef corals: insights from the last Pleistocene interglacial

**The Palaeontological Association: Progressive Palaeontology** (Manchester, UK, 2018)  
Oral: Coupling palaeontological and neontological data: transitional distribution ranges of reef corals under global climatic change

**The Palaeontological Association: Annual Meeting** (London, UK, 2017)  
Poster: Ecological niche modelling in deep time: constraining the transitional distribution ranges of reef corals

**European Coral Reef Symposium** (Oxford, UK, 2017)  
Poster: Anthropogenic climate change and transitional distribution ranges of reef corals: insights from the last Pleistocene interglacial

**The Palaeontological Association: Progressive Palaeontology** (Leicester, UK, 2017)  
Poster: PalaeoENM: Ecological Controls on Triassic/Jurassic Coral Reefs

## Fieldwork experience

**El Qoseir, Egypt** (2023)  
Modern and fossil (Last Interglacial) coral reef data collection via line-intercept transects

**León, Spain** (2022)  
Logging and bulk sampling of Devonian sequences

**Colorado and New Mexico, USA** (2016)  
Logging, sampling, and fossil prospecting across the Cenomanian/Turonian boundary

**Somerset, Lyme Regis, and Newark, UK** (2015)  
Logging, sampling, and geochemical analysis across the Triassic/Jurassic boundary

**Koh Rong, Cambodia** (2012)  
Marine biological surveys as part of Koh Rong's (Cambodia) coral reef monitoring project

## Professional development

**Macroevolution and Phylogenies** (2022)  
Transmitting Science, Online

**Introduction to GEN3SIS** (2022)  
Universidade de Vigo, Vigo, Spain

**Towards more equitable marine research** (2021)  
Centro de Investigación Mariña (led by Transmitting Science), Universidade de Vigo, Spain

**Data manipulation and Statistical Analysis in Palaeoecology** (2021)  
Palaeoecology Group, British Ecological Society, Online

**Doctoral Summer School for Advanced Spatial Modelling** (2019)  
The Centre for Advanced Spatial Analysis, University College London, London, UK

**Species distribution modelling: fundamentals and the future workshop** (2019)  
University of Nottingham, Nottingham, UK

**Advanced ecological niche modelling** (2018)  
University of Porto, Porto, Portugal

**Introduction to ecological niche modelling** (2017)  
Transmitting Science, Barcelona, Spain

**Introduction to coral identification** (2017)  
European Coral Reef Symposium, Oxford, UK

**Introduction to larval dispersal modelling** (2017)  
European Coral Reef Symposium, Oxford, UK

## Student supervision

**Theres Koch** (2024)  
University of Vienna, Austria   
Master's project: Checklist of scleractinian species in Mangrove Bay, El Qoseir, Egypt

**Miranta Kouvari** (2019&ndash;2023)  
University College London, London, UK  
Master's project: The latitudinal biodiversity gradient of South American eutherians

**Lucas Buffan** (2021&ndash;2022)  
University of Vigo, Vigo, Spain  
Master's project: Spatial discrepancies in palaeogeographic reconstructions

## Teaching and pastoral care

**R for Paleobiologists: Getting Started with the palaeoverse R Package** (2024)  
12<sup>th</sup> North American Paleontological Convention, Ann Arbor, Michigan, USA 
Organised and ran a workshop on using R in Palaeobiology

**Lab Assistant** (2024)  
Universidade de Vigo, Vigo, Spain  

-  Computational Tools in Biology

**R for Palaeobiologists: Workshop and Hackathon** (2023)  
University College London, UK  
Organised and ran a workshop on using R in Palaeobiology

**Graduate Teaching Assistant** (2016&ndash;2021)  
Imperial College London, London, UK

-   Palaeobiology I
-   Palaeobiology II
-   Dorset (UK) geology field course
-   Almería (Spain) geology field course

**Student Hall's Warden** (2016&ndash;2021)  
Woodward Buildings, Imperial College London, London, UK

## Professional service and outreach

**Recent Advances in Computational Paleobiology symposium** (Ann Arbor, Michigan, USA, 2024)  
Co-organised and ran a symposium at the 12<sup>th</sup> North American Paleontological Convention

**Palaeoverse Lecture Series** (2024–Current)  
Monthly lecture series on recent advances in computational tools and methods in palaeobiology [https://www.youtube.com/@ThePalaeoverse/](https://www.youtube.com/@ThePalaeoverse/)

**14<sup>th</sup> International Fossil Coral and Reef Society symposium** (Chęciny, Poland, 2023)  
Session chair: Fossil coral reefs: research methods

**IFCRS Internet Officer** (2023&ndash;current)  
Committee member of the International Fossil Coral and Reef Society (IFCRS)

**IFCRS Early Career Researcher Representative** (2021&ndash;2023)  
Committee member of the International Fossil Coral and Reef Society (IFCRS)

**IFCRS Lecture Series** (2022)  
International Fossil Coral and Reef Society, Online  
Co-organised and ran a lecture series on fossil corals and reefs

**IFCRS Early Career Researcher Symposium** (2021)  
International Fossil Coral and Reef Society, Online  
Co-organised and ran an early career researcher meeting on fossil corals and reefs

**Fossil Fact or Fiction stall** (2019)  
Einstein's Garden, Green Man Festival, Brecon Beacons, Wales  
Co-ran a stall on fossil record bias over the course of the festival

**Ecological niche modelling workshop** (2018)  
Imperial College London, London, UK  
Co-organised and ran a workshop on ecological niche modelling

**Palaeontological Association meeting** (2017)  
Imperial College London, London, UK  
Co-organised and ran the annual meeting of the Palaeontological Association

## Peer-review experience

*Ecological Monographs* 
*Global Ecology and Biogeography*  
*Journal of Biogeography*  
*Methods in Ecology and Evolution*  
*Nature Communications*  
*Science Advances*  
*Scientific Reports*  
*Trends in Ecology and Evolution*  

## Skills

**R programming**  
Advanced proficiency in data analysis, data visualization, writing functions and developing packages

**Geocomputation**  
Proficient in spatial analysis and the use of R spatial packages (e.g. raster, terra, sf, sp)

**Languages**  
Spanish (CEFR B1)  
Mandarin Chinese (HSK1)

**SCUBA diver**  
BSAC-accredited Ocean and Sports Diver

**Workplace qualifications**  
Emergency first-aid at work & automated external defibrillator  
Outdoors emergency first-aid  
Mental health first-aid  
Fire safety and warden  
Active-bystander

**Driving**  
Full EU driving license

## Memberships

Member of the International Fossil Coral and Reef Society (2018&ndash;present)  
Member of the Palaeontological Association (2017&ndash;present)  
Member of the Paleontological Society (2023&ndash;present)  
Member of the Conservation Paleobiology Network (2019&ndash;present)  
Member of the British Ecological Society (2017&ndash;present)
