---
pagetitle: Publications
editor: source
toc: false
link-external-icon: false
---

# Publications

## **Peer-reviewed publications**

1. Christopher D. Dean, Alfio A. Chiarenza, Jeffrey W. Doser, Alexander Farnsworth, **Lewis A. Jones**, Sin&eacute;ad J. Lyster, Charlotte L. Outhwaite, Paul J. Valdes, Richard J. Butler, and Philip D. Mannion (2025). The structure of the end-Cretaceous dinosaur fossil record in North America. *Current Biology* 35(9), 1973&ndash;1988. DOI: [10.1016/j.cub.2025.03.025](https://doi.org/10.1016/j.cub.2025.03.025).

2. Theres Koch, Angelina Ivki&cacute;, **Lewis A. Jones**, Victor S. Scharnhorst, Constanze M. Stix, Antonia Auer, Theda Sch&ouml;chtner, G&ouml;zde &Ouml;zer, Simon Steinwender, Joseph W. Daurella, and Martin Zuschin (2025). Quantifying diversity and growth form distribution of scleractinian corals, in Mangrove Bay, El Qoseir, Egypt. *Biodiversity Data Journal* 13, e134282. DOI: [10.3897/BDJ.13.e134282](https://doi.org/10.3897/BDJ.13.e134282).

3. **Lewis A. Jones**, Christopher D. Dean, William Gearty, and Bethany J. Allen (2024). rmacrostrat: An R package for accessing and retrieving data from the Macrostrat geological database. *Geosphere* 20(6), 1456&ndash;1467. DOI: [10.1130/GES02815.1](https://doi.org/10.1130/GES02815.1).

4. **Lewis A. Jones** and Mathew Domeier (2024). A Phanerozoic gridded dataset for palaeogeographic reconstructions. *Scientific Data* 11 (710), 1&ndash;7. DOI: [10.1038/s41597-024-03468-w](https://doi.org/10.1038/s41597-024-03468-w).

5.	Alfio A. Chiarenza, Juan L. Cantalapiedra, **Lewis A. Jones**, Sara Gamboa, Sofía Galván, Alexander Farnsworth, Paul J. Valdes, Graciela Sotelo, and Sara Varela (2024). Early Jurassic origin of avian endothermy and thermophysiological diversity in dinosaurs. *Current Biology* 34, 1&ndash;11. DOI: [10.1016/j.cub.2024.04.051](https://doi.org/10.1016/j.cub.2024.04.051).

6.	Kilian Eichenseer and **Lewis A. Jones** (2024). Bayesian multi-proxy reconstruction of early Eocene latitudinal temperature gradients. *Climate of the Past* 20, 349&ndash;362. DOI: [10.5194/cp-20-349-2024](https://doi.org/10.5194/cp-20-349-2024).

7.  Lucas Buffan, **Lewis A. Jones**, Mathew Domeier, Christopher R. Scotese, Sabin Zahirovic and Sara Varela (2023). Mind the Uncertainty: Global Plate Model choice impacts deep-time palaeobiological studies. *Methods in Ecology and Evolution* 14 (12), 3007&ndash;3019. DOI:[10.1111/2041-210X.14204](https://doi.org/10.1111/2041-210X.14204).

8.  William Gearty and **Lewis A. Jones** (2023). rphylopic: An R package for fetching, transforming, and visualising PhyloPic silhouettes. *Methods in Ecology and Evolution* 14 (11), 2700&ndash;2708. DOI:[10.1111/2041-210X.14221](https://doi.org/10.1111/2041-210X.14221).

9.  **Lewis A. Jones**, William Gearty, Bethany J. Allen, Kilian Eichenseer, Christopher D. Dean, Sofía Galván, Miranta Kouvari, Pedro L. Godoy, Cecily Nicholl, Lucas Buffan, Erin M. Dillon, Joseph T. Flannery-Sutherland and A. Alessandro Chiarenza (2023). palaeoverse: A community-driven R package to support palaeobiological analysis. *Methods in Ecology and Evolution* 14 (9), 2205&ndash;2215. DOI:[10.1111/2041-210X.14099](https://doi.org/10.1111/2041-210X.14099).

10.  **Lewis A. Jones**, Philip D. Mannion, Alexander Farnsworth, Fran Bragg, Daniel J. Lunt (2022). Climatic and tectonic drivers shaped the tropical distribution of coral reefs. *Nature Communications* 13 (3120), 1&ndash;10. DOI:[10.1038/s41467-022-30793-8](https://doi.org/10.1038/s41467-022-30793-8).

11.  **Lewis A. Jones** and Kilian Eichenseer (2022). Uneven spatial sampling distorts reconstructions of Phanerozoic seawater temperature. *Geology* 50 (2), 238&ndash;242. DOI:[10.1130/G49132.1](https://doi.org/10.1130/G49132.1).

12.  **Lewis A. Jones**, Christopher D. Dean, Philip D. Mannion, Alexander Farnsworth, Peter A. Allison (2021). Spatial sampling heterogeneity limits the detectability of deep time latitudinal biodiversity gradients. *Proceedings of the Royal Society B* 288 (1945), 20202762. DOI:[10.1098/rspb.2020.2762](https://doi.org/10.1098/rspb.2020.2762).

13.  **Lewis A. Jones**, Philip D. Mannion, Alexander Farnsworth, Paul Valdes, Sarah-Jane Kelland, and Peter A. Allison (2019). Coupling of palaeontological and neontological reef coral data improves forecasts of biodiversity responses under global climatic change. *Royal Society Open Science* 6 (4), 182111. DOI:[10.1098/rsos.182111](https://doi.org/10.1098/rsos.182111).

14.  Alfio Alessandro Chiarenza, Philip D. Mannion, Daniel Lunt, Alexander Farnsworth, **Lewis A. Jones**, Sarah-Jane Kelland, and Peter A. Allison (2019). Ecological niche modelling does not support climatically-driven dinosaur diversity decline before the Cretaceous/Paleogene mass extinction. *Nature Communications* 10 (1091), 1&ndash;14. DOI:[10.1038/s41467-019-08997-2](https://doi.org/10.1038/s41467-019-08997-2).

## **Theses**

1.  **Lewis A. Jones** (2020). On the detectability of latitudinal biodiversity gradients in deep time. PhD Thesis. Imperial College London. Supervisors: Prof. Philip D. Mannion and Prof. Peter A. Allison. DOI:[10.25560/100239](https://spiral.imperial.ac.uk/handle/10044/1/100239).

2.  **Lewis A. Jones** (2015). The end-Triassic mass extinction. An investigation of the British geological record: testing for the role of volcanism and ocean anoxia. Master Thesis. Supervisor: Prof. David Bond.

## **Other works**

1. **Lewis A. Jones**, Christopher D. Dean, and Harriet B. Drage (2025). [Introducing the Palaeoverse](https://www.palass.org/publications/newsletter/archive/118/newsletter-no-118). *The Palaeontological Association Newsletter* 118.

2. **Lewis A. Jones** (2024). [Meeting report: R for Palaeobiologists: Workshop and Hackathon](https://www.palass.org/publications/newsletter/archive/116/newsletter-no-116). *The Palaeontological Association Newsletter* 116.

3.  **Lewis A. Jones** (2023). [Palaeontology’s greatest ever graphs: The absence of evidence: spatial sampling bias in the fossil record](https://www.palass.org/publications/newsletter/archive/114/newsletter-no-114). *The Palaeontological Association Newsletter* 114.

4.  **Lewis A. Jones** (2022). [Book review: Timefulness: How thinking like a geologist can help save the world](https://www.palass.org/publications/newsletter/archive/110/newsletter-no-110). *The Palaeontological Association Newsletter* 110.

5.  Michael Stevens, Yiqiao Chen, Alex Stringer, Caitlin Clemmow, and **Lewis A. Jones** (2020). [Key factors driving obesity in the UK](https://drive.google.com/file/d/1MHWMo_bC1pw-hVEddibDvxsinlOK0Tjh/view). *GISRUK* 2020.

6.  **Lewis A. Jones** (2020). [Meeting report: 13th International Symposium of Fossil Cnidaria and Porifera](https://www.palass.org/sites/default/files/media/publications/newsletters/number_102/number_102.pdf). *The Palaeontological Association Newsletter* 102.